name: Laravel

on:
  pull_request:
    branches: ["master"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    container:
      image: ggmartinez/laravel:php-82
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate
      - name: Create Database
        env:
          DB_HOST: mysql
        run: php artisan migrate
      - name: Seed Database
        env:
          DB_HOST: mysql
        run: php artisan db:seed
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_HOST: mysql
        run: php artisan test
